com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.hasMoreChildren(AbstractPullReader.java:87)
	at com.intellij.database.model.serialization.FixHierarchicalStreamReader.hasMoreChildren(FixHierarchicalStream.kt)
	at com.intellij.database.model.serialization.ModelImporter.deserializeObject(ModelImporter.java:165)
	at com.intellij.database.model.serialization.ModelImporter.deserializeModel(ModelImporter.java:118)
	at com.intellij.database.model.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:25)
	at com.intellij.database.model.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:15)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:725)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:713)
	at com.intellij.database.dataSource.DataSourceStorage.loadModels(DataSourceStorage.java:522)
	at com.intellij.database.dataSource.DataSourceStorage.readStateHeavy(DataSourceStorage.java:417)
	at com.intellij.database.dataSource.DataSourceStorage.access$000(DataSourceStorage.java:89)
	at com.intellij.database.dataSource.DataSourceStorage$2.run(DataSourceStorage.java:401)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.xmlpull.v1.XmlPullParserException: unexpected character in markup < (position: START_TAG seen ...<database id="7" parent="1" name="plateform">\n<<... @28:3) 
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1261)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 27 more
